topology-gg/shoshin

8-zed/contracts/constants.cairo
8-zed/contracts/engine.cairo
8-zed/contracts/utils.cairo
8-zed/experiments/agent.json
8-zed/experiments/null_agent.json
8-zed/tests/test_engine.py
8-zed/tests/utils.py
README.md

Feat state machine

---

.gitignore
.gitmodules
8-zed/contracts/constants/constants.cairo
8-zed/contracts/dynamics.cairo
8-zed/contracts/engine.cairo
8-zed/contracts/utils.cairo
8-zed/experiments/advanced_agent.json
8-zed/tests/test_engine.py

Feat agent dogfood

---

8-zed/contracts/constants/constants.cairo
8-zed/contracts/engine.cairo
8-zed/tests/test_engine.py

feat: metadata

---

8-zed/contracts/dynamics.cairo
8-zed/contracts/physics.cairo
8-zed/tests/test_engine.py

Fixes the errors from overlapping agents with one agent in knocked state.

Fix y axis physic

---

8-zed/contracts/engine.cairo
Makefile
scripts/compile_cairo.sh
scripts/compile_lib.sh
scripts/gencairo.py
scripts/genlib.py

Add script allowing to generate the pure cairo bytecode from the starknet contract.
Documentation for the script is available in Makefile

feat: cairo script

---

8-zed/contracts/body/body.cairo
8-zed/contracts/body/body_antoc.cairo
8-zed/contracts/body/body_jessica.cairo
8-zed/contracts/body/body_utils.cairo
8-zed/contracts/constants/constants.cairo
8-zed/contracts/constants/constants_antoc.cairo
8-zed/contracts/constants/constants_jessica.cairo
8-zed/contracts/engine.cairo
8-zed/protostar.toml
8-zed/tests/body/body_antioc/test_body_antioc.cairo
8-zed/tests/body/body_antioc/test_body_antioc_stamina.cairo
8-zed/tests/body/body_antioc/test_body_antioc_stimulus.cairo
8-zed/tests/body/body_jessica/test_body_jessica_stamina.cairo
8-zed/tests/body/body_jessica/test_body_jessica_stimulus.cairo
8-zed/tests/body/test_body_utils.cairo

Stamina 
Idle, walking and blocking nets the character stamina. Each frame in these actions provides stamina.
Attacking and Dashing cost stamina upfront in order to execute the move. If a character does not have sufficient stamina to perform what it intends then the character either continues the current action or returns to IDLE.
Max Stamina : 1000
Integrity
Being Hurt or Knocked costs the character 100 integrity. 
Max Integrity : 1000
----
What happens when fatigued?
Cancellable moves (not last frame) - 
-  increment the counter
- indicate fatigue
Last Frame (with ability to act again) -
- go to IDLE
- indicate fatigue
During actions that recover stamina -
- increment counter/continue action
- indicate fatigue

Health and stamina

---

8-zed/contracts/physics.cairo
8-zed/protostar.toml
8-zed/tests/dynamics/test_dynamics.cairo
8-zed/tests/test_engine.py

This PR includes:
- The fix to the hitboxes of agents overlapping
- Unit testing on euler_forward_consider_hitbox to verify overlapping is solved

fix: dash overlap

---

8-zed/contracts/engine.cairo
scripts/README.md
scripts/gencairo.py

This PR updates the metadata event to emit both agents' description. Also adds an update to the pure Cairo compilation script (see README for information on use).

feat: events

---

8-zed/contracts/engine.cairo
scripts/deploy.sh

This PR includes the function call and event for single agent submission as well as a deploy script.

feat: submit agent

---

8-zed/contracts/body/body_antoc.cairo
8-zed/contracts/body/body_jessica.cairo
8-zed/contracts/constants/constants_antoc.cairo
8-zed/contracts/constants/constants_jessica.cairo
8-zed/contracts/dynamics.cairo
8-zed/contracts/engine.cairo

feat: update dash

---

8-zed/contracts/engine.cairo
scripts/deploy.sh

This PR adds name registering for mental states and conditions.

feat: name conditions and mental states

---

8-zed/contracts/combo.cairo
8-zed/contracts/constants/constants.cairo
8-zed/contracts/engine.cairo

This PR adds comments to the combo function and adds combo to the emitted frame event.

feat: add combo to emitted frame events

---

scripts/build_lib.sh

This PR updates the `evaluate_condition` script in order to dump the correct cairo code.

fix: update evaluate_condition script

---

8-zed/contracts/body/body_antoc.cairo
8-zed/contracts/body/body_jessica.cairo
8-zed/contracts/constants/constants.cairo

- Antoc's body responds to CLASH stimulus when in HORI or VERT state.
- Both Antoc and Jessica experiences integrity decrease when going into CLASH state

Make Antoc respond to stimulus; add stimulus effect to integrity

---

8-zed/contracts/perceptibles.cairo

test by making sure agent-19 stays in its initial state

add sta to update_perceptibles

---

8-zed/contracts/constants/constants.cairo
8-zed/contracts/engine.cairo

Refer to [Tooling PR](https://github.com/topology-gg/shoshin-tooling/pull/134) for documentation

real time agent combo

---

8-zed/contracts/body/body_antoc.cairo
8-zed/contracts/body/body_jessica.cairo
8-zed/contracts/constants/constants.cairo

This PR makes:
- block sustained at active frame as long as intent stays at BLOCK
- staying in block consume stamina every frame

Make block sustained and consume stamina

---

8-zed/contracts/constants/constants_antoc.cairo
8-zed/contracts/constants/constants_jessica.cairo

So that it takes 1 frame from static to max velocity, and two frames to switch direction from minus max velocity to positive max velocity.

Increase move acceleration

---

8-zed/contracts/body/body_antoc.cairo
8-zed/contracts/body/body_jessica.cairo

It makes sense to make clash state vulnerable to being hit and hurt / knocked.

Make clash interruptible

---

8-zed/contracts/engine.cairo

0 integrity agents would keep fighting in simulation mode.

set integrity left bound to 1

---

8-zed/contracts/constants/constants_antoc.cairo
8-zed/contracts/constants/constants_jessica.cairo
8-zed/contracts/physics.cairo

This PR refactors contract logic that computes the position and dimension of body hitbox and action hitbox, and fine tune the hitbox for each move of each character.

Contract update: move-specific hitboxes

---

8-zed/contracts/body/body_antoc.cairo
8-zed/contracts/body/body_jessica.cairo
8-zed/contracts/body/body_utils.cairo
8-zed/contracts/constants/constants.cairo
8-zed/contracts/constants/constants_antoc.cairo
8-zed/contracts/constants/constants_jessica.cairo
8-zed/contracts/physics.cairo

This PR:
- implements low kicks for both characters, and makes sure low kick can break block.
- reduces stamina cost for movement eg dashing to make resource management easier for now

Low kicks + stamina cost adjustments

---

8-zed/contracts/body/body_antoc.cairo
8-zed/contracts/body/body_jessica.cairo
8-zed/contracts/body/body_utils.cairo
8-zed/contracts/constants/constants.cairo
8-zed/contracts/constants/constants_antoc.cairo
8-zed/contracts/constants/constants_jessica.cairo
8-zed/contracts/dynamics.cairo
8-zed/contracts/physics.cairo

Air attacks + landing bug + more launch

---

8-zed/contracts/body/body_antoc.cairo
8-zed/contracts/body/body_jessica.cairo
8-zed/contracts/body/body_utils.cairo
8-zed/contracts/constants/constants.cairo
8-zed/contracts/constants/constants_antoc.cairo
8-zed/contracts/constants/constants_jessica.cairo
8-zed/contracts/physics.cairo

- Antoc's special Cyclone is 18 frames long. active when counter == 5 and 10.
- block no longer drains rage.

Antoc special: Cyclone

---

8-zed/contracts/body/body_antoc.cairo
8-zed/contracts/body/body_jessica.cairo
8-zed/contracts/constants/constants_antoc.cairo
8-zed/contracts/constants/constants_jessica.cairo

- Increase Upswing length from 5 to 8 frames, with recovery prolonged
- Jessica's dash cancelled into attack's active frame - 1 instead of active frame
- Antoc's step forward cancelled at 2nd frame, not 1st frame

Adjust frames

---

8-zed/contracts/body/body_antoc.cairo
8-zed/contracts/body/body_utils.cairo
8-zed/contracts/constants/constants_antoc.cairo

This PR implements taunt for antoc.

antoc taunt

---

8-zed/contracts/constants/constants_antoc.cairo
8-zed/contracts/constants/constants_jessica.cairo
8-zed/contracts/dynamics.cairo
8-zed/contracts/physics.cairo

This PR fixes the physics asymmetry problem.
1. Use the X midpoint of the body as physics position X.
2. Update logic that computes hitbox position and calculates overlap amount.

Physics asymmetry (MERGE BY GG)

---

8-zed/contracts/combo.cairo
8-zed/contracts/constants/constants.cairo
8-zed/contracts/engine.cairo
8-zed/contracts/utils.cairo

Support action randomness. Limit to two options per state/layer.
Note: postpone support for real time mode `playerInLoop()` action randomness

Action randomness

---

8-zed/contracts/body/body_antoc.cairo
8-zed/contracts/body/body_jessica.cairo
8-zed/contracts/constants/constants.cairo
8-zed/contracts/engine.cairo
8-zed/contracts/physics.cairo

This PR encodes grounded signal separately within stimulus.
Before this, a character receiving a HURT/KNOCKED/LAUNCHED etc stimulus would be considered ungrounded, which causes weird behavior such as birdswing on the ground.

Grounded signal

---

8-zed/contracts/constants/constants.cairo
8-zed/contracts/constants/constants_antoc.cairo
8-zed/contracts/constants/constants_general.cairo
8-zed/contracts/constants/constants_jessica.cairo
8-zed/contracts/dynamics.cairo

This PR adds little forward nudge to character attacking - hori, vert, lowkick, sidecut, upswing, slash.

Nudge character attacking

---

8-zed/contracts/body/body_antoc.cairo
8-zed/contracts/body/body_jessica.cairo

The attacker getting clashed or knocked, particularly from the opponent good-blocking, now happens correctly.

Fix clash & knock
